### ISSUE TITLE
[Table of Contents] truncated  in 2017-03-02 .mobi version

### ISSUE THREAD

**Issue by JESii** [survivejs/react-book#434]
When I go to view the Table of Contents (.mobi version on iPad Kindle) all I see is:
```
Table of Contents
  Introduction
```
Is this expected and planned for a later update?

**Comment by bebraw** [comment]
Hi,

That might be a Leanpub bug. I have to take a closer look to see what's going on.

**Comment by bebraw** [comment]
Wait, that's all you see? No pages beyond that?

Looks fine on my iPad. Hmm.

**Comment by bebraw** [comment]
I downloaded the version from Leanpub (should be the same I just reviewed) and can't see the issue on iPad Kindle. I'm going to need more information to debug.

You can also contact Leanpub (hello@leanpub.com) as it could be something on their side.

**Comment by JESii** [comment]
Juno... Here's the screenshot; there's nothing below this

I'll post a note to lean pub as well.

...Jon

**Comment by JESii** [comment]
No... I see a bunch of pages in the book itself; it's just that the TOC only shows the introduction section and nothing else; sending you the screenshot separately from my ipad
