### ISSUE TITLE
[4.2 - app/components/Note.jsx] - Extra 'value:' text in screenshot

### ISSUE THREAD

**Issue by JESii** [survivejs/react-book#436]
After the initial changes for Note/delete, you show a screenshot with the delete 'x' display. Good.

However, that screenshot also includes the text 'value:' preceding each task; I don't see that in my follow-along version.
Yours:
![image](https://cloud.githubusercontent.com/assets/486/26112973/1dea87c6-3a0e-11e7-8510-77684d1c344d.png)

Mine:
![image](https://cloud.githubusercontent.com/assets/486/26113008/3143a3d4-3a0e-11e7-8342-71cfc4fe9389.png)

**Comment by bebraw** [comment]
Good call. I think I have to redo the screenshot. I have a bigger refactoring in mind so that's a good place to do it. Thanks.

**Comment by bebraw** [comment]
Good call. I think I have to redo the screenshot. I have a bigger refactoring in mind so that's a good place to do it. Thanks.
