### ISSUE TITLE
[I 6.5 - Tracking Note editing State] - Error on click to finish editing

### ISSUE THREAD

**Issue by JESii** [survivejs/react-book#439]
At the end of this section, you say "If you click a `Note` twice to confirm the edit, you should see an `Uncaught Invariant Violation` error..."

Instead, when I click the `Note` once, I get this error:
![image](https://cloud.githubusercontent.com/assets/486/26277296/a1abd0fe-3d3a-11e7-8886-f036ffe89064.png)

Commit with the code is [here](https://github.com/JESii/survivejs-kanban-app/commit/67df1d49ba9bb891b86768a995c34852f6794076)

**Comment by bebraw** [comment]
Yeah, looks like the error changed in React 15. Good point.

**Comment by JESii** [comment]
At some point, I think you're gonna have to pick a release and just stick with it -- else you could go nuts trying to keep up with this.

With webpack and package.json, couldn't you just 'freeze' things in a known state and have a reliable target?

**Comment by bebraw** [comment]
A big rewrite is needed anyhow so it's good you open these issues. 👍

**Comment by JESii** [comment]
OK; I'll call 'em as I sees 'em :=)
