### ISSUE TITLE
[I 6.6 - Implementing Edit] - parameter order & {true}

### ISSUE THREAD

**Issue by JESii** [survivejs/react-book#440]
1) In this section, you change
`const Edit = ({onEdit = () => {}, value, ...props}) => (`
to
`const {value, onEdit, ...props} =`
Why the change in the order of parameters? And wouldn't that matter?

2) Later, in the `return` statement you have:
`autoFocus={true}`
Why is true enclosed in {}? Since it's a constant, shouldn't that just be:
`autoFocus=true`? 
I mean, it'll work ok because it is a constant...

**Comment by bebraw** [comment]
1. The order doesn't matter.
2. I would write just `autoFocus` now as that's equivalent. I think I used braces so it's consistent.

**Comment by JESii** [comment]
Got it; thanks!

**Comment by JESii** [comment]
Actually, the braces ARE required -- without them you get this error from the build step:
`Module build failed: SyntaxError: JSX value should be either an expression or a quoted JSX text (22:13)`

**Comment by bebraw** [comment]
@JESii Yeah. But note that `autoFocus={true}` and `autoFocus` are equivalent based on the current JSX specification.
