### ISSUE TITLE
[Section I] - general question about usage on bind()

### ISSUE THREAD

**Issue by JESii** [survivejs/react-book#441]
In your code, you use the form `function.bind(null, callback)`, whereas the examples in the React documentation (e.g., [here](https://facebook.github.io/react/docs/handling-events.html) and [here](https://facebook.github.io/react/docs/conditional-rendering.html)) just use `function.bind(callback)`.

Why is that? This is most likely just my lack of JavaScript knowledge; however, I would like to understand it better and it might help other readers? Thanks!

**Comment by bebraw** [comment]
It's how [the specification](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind) works. The first parameter accepts the context and the second parameter(s).

You can see bits like `this.handleLoginClick = this.handleLoginClick.bind(this);` in the React docs at constructors and they leave parameters unbound there.
